# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e040832a7dfb59960afd43e128fce9ec27e6ec54c1b97ae206b024ebb222b48b1a8e28bd33bec06aaaa61f636f800b34d663523d373c1e9d16ed9c519f2360b9

test:
  secret_key_base: 360320632c5d31882b5e32fd7754f19b06ea1d3759044d6eb40bcc7ba6f6c93aed244cb71f809cc8c0fa8040f55ebf6bc2c47d243c72ffdbe2ea6927a60fdbce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
